
[font]
size = 16

[mouse]
hide_when_typing = true

[window]
decorations = "Full"
opacity = 0.9
blur = true

[keyboard]
bindings = [
  { key = "Return", mods = "Shift", chars = "\u001b\r" },
  # Alt+Left: move back one word
  { key = "Left", mods = "Alt", chars = "\u001bb" },
  # Alt+Right: move forward one word
  { key = "Right", mods = "Alt", chars = "\u001bf" },
  # Alt+Backspace: delete word backward
  { key = "Back", mods = "Alt", chars = "\u001b\u007f" }
]

[general]
# Import catppuccin theme
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]
