# Import catppuccin theme
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[font]
size = 16

[mouse]
hide_when_typing = true

[window]
decorations = "Full"
opacity = 0.9
blur = true

[keyboard]
bindings = [
  { key = "Return", mods = "Shift", chars = "\u001b\r" }
]
